### ISSUE TITLE
Allow exclusive communication

### ISSUE THREAD

**Issue by intrikate** [khoogheem/USBManager#1]
It may be necessary for some devices to be open for exclusive communication (“seized”), which the current interface doesn’t provide for.

Importantly, opening a device using `kIOHIDOptionsTypeSeizeDevice` doesn’t seem to suffice unless the manager itself is set to seize (in fact, this option seems to be ignored entirely on `IOHIDDevice`). Understandably, this isn’t something that should be done on a shared instance, meaning the implementation would imply a certain change in the public interface.

I’d be willing to make a PR if this is something you might be interested in.

**Comment by khoogheem** [comment]
I am no longer using or maintaining this... gonna archive it..

Thanks
